echo "*************************************"
echo "                                     "
echo "Welcome To Flight Management System."
echo "                                     "
echo "*************************************"